export const ENVIRONMENTS = [
  "coffee shop",
  "subway platform",
  "library reading room",
  "university classroom",
  "park bench",
  "supermarket aisle",
  "street market",
  "office pantry",
  "coworking space",
  "gym reception",
  "yoga studio lobby",
  "bus stop",
  "train carriage",
  "taxi",
  "rideshare",
  "airport check-in",
  "boarding gate",
  "airplane aisle",
  "hotel lobby",
  "elevator",
  "corridor",
  "rooftop garden",
  "museum gallery",
  "cinema queue",
  "theater lobby",
  "concert venue",
  "sports stadium",
  "swimming pool deck",
  "beach promenade",
  "hiking trail",
  "campsite",
  "bookstore",
  "electronics store",
  "clothing boutique",
  "fitting room area",
  "pharmacy",
  "bank queue",
  "post office",
  "DMV waiting room",
  "courthouse lobby",
  "hospital waiting room",
  "clinic reception",
  "dentist office",
  "daycare pickup area",
  "school hallway",
  "university quad",
  "dorm common room",
  "cafeteria",
  "canteen",
  "food truck line",
  "farmers market",
  "kitchen supply store",
  "hardware store",
  "home improvement aisle",
  "furniture showroom",
  "pet store",
  "dog park",
  "veterinary clinic",
  "community center",
  "church foyer",
  "temple courtyard",
  "playground",
  "skating rink",
  "bowling alley",
  "arcade",
  "karaoke room",
  "photo booth area",
  "festival food court",
  "street fair",
  "charity event desk",
  "volunteer center",
  "police station front desk",
  "fire station open day",
  "city hall info desk",
  "embassy waiting room",
  "language exchange meetup",
  "book club circle",
  "cooking class kitchen",
  "art workshop studio",
  "music practice room",
  "recording studio reception",
  "tv station lobby",
  "radio station booth foyer",
  "newsroom bullpen",
  "tech conference hallway",
  "startup demo day",
  "career fair booth",
  "networking mixer",
  "speed dating event",
  "wedding reception",
  "tailor shop",
  "cobbler counter",
  "barber shop",
  "hair salon",
  "nail salon",
  "spa lounge",
  "sauna anteroom",
  "laundromat",
  "dry cleaner counter"
] as const
export const environments = ENVIRONMENTS

export const RELATIONSHIP_TYPES = [
  "friend",
  "coworker",
  "classmate",
  "neighbor",
  "stranger",
  "shop assistant",
  "customer",
  "teacher",
  "student",
  "roommate",
  "sibling",
  "parent",
  "child",
  "partner",
  "ex-partner",
  "teammate",
  "coach",
  "manager",
  "direct report",
  "recruiter",
  "interviewer",
  "landlord",
  "tenant",
  "delivery driver",
  "barista",
  "server",
  "cashier",
  "receptionist",
  "tour guide",
  "tourist",
  "doctor",
  "nurse",
  "pharmacist",
  "librarian",
  "security guard",
  "rideshare driver",
  "commuter",
  "gym trainer",
  "client",
  "vendor",
  "mentor",
  "mentee",
  "online acquaintance",
  "language partner"
] as const
export const relationshipTypes = RELATIONSHIP_TYPES

export const TRIGGER_EVENTS = [
  "spilled coffee",
  "lost item found",
  "late for appointment",
  "missed stop",
  "incorrect order",
  "power outage",
  "sudden rain",
  "fire alarm test",
  "elevator stuck briefly",
  "surprise announcement",
  "flash sale",
  "street performer draws crowd",
  "dog breaks leash",
  "child crying nearby",
  "phone low battery alert",
  "app glitch",
  "map reroute",
  "bump into acquaintance",
  "name called by staff",
  "seat becomes available",
  "queue opens",
  "doors closing soon",
  "train delay",
  "bus rerouted",
  "new message popup",
  "device pairing request",
  "mispronunciation correction",
  "overheard interesting topic",
  "ask for directions",
  "ask to take a photo",
  "dropped wallet",
  "misplaced ticket",
  "promo code not working",
  "reservation mix-up",
  "overcharged bill",
  "undercharged bill",
  "wrong seat assignment",
  "double booking",
  "crowd forming",
  "line cut dispute",
  "sound system failure",
  "microphone feedback",
  "weather warning",
  "health check request",
  "security bag check",
  "id verification",
  "language misunderstanding",
  "delivery mix-up",
  "package missing",
  "keycard not working"
] as const
export const triggerEvents = TRIGGER_EVENTS

export const EMOTIONAL_STATES = [
  "neutral",
  "happy",
  "excited",
  "anxious",
  "stressed",
  "annoyed",
  "frustrated",
  "embarrassed",
  "curious",
  "bored",
  "tired",
  "confident",
  "shy",
  "determined",
  "cautious",
  "apologetic",
  "grateful",
  "disappointed",
  "amused",
  "confused",
  "irritated",
  "supportive"
] as const
export const emotionalStates = EMOTIONAL_STATES

export const BEHAVIOR_STRATEGIES = [
  "polite small talk",
  "direct and concise",
  "humorous icebreaker",
  "empathetic listening",
  "assertive boundary setting",
  "inquisitive questioning",
  "reflective paraphrasing",
  "solution brainstorming",
  "de-escalation",
  "positive reinforcement",
  "storytelling",
  "share personal experience",
  "offer help",
  "seek clarification",
  "mirror tone",
  "gradual disclosure",
  "redirect topic",
  "negotiate compromise",
  "set expectations",
  "encourage participation",
  "timebox conversation",
  "summarize next steps"
] as const
export const behaviorStrategies = BEHAVIOR_STRATEGIES

export const INITIATIVE_ACTIONS = [
  "greet first",
  "ask open question",
  "give compliment",
  "offer seat",
  "hold door",
  "introduce self",
  "ask for directions",
  "request recommendation",
  "comment on weather",
  "ask about wait time",
  "volunteer assistance",
  "share resource",
  "propose plan",
  "apologize for inconvenience",
  "clarify misunderstanding",
  "make small request",
  "escalate to staff",
  "exchange contact info",
  "suggest follow-up",
  "close with thanks"
] as const
export const initiativeActions = INITIATIVE_ACTIONS

export const CLOSURE_REASONS = [
  "class starting",
  "bus arriving",
  "meeting starting",
  "phone call interrupting",
  "someone else calling the character",
  "train arriving",
  "order ready",
  "appointment time",
  "battery dying",
  "announcement starting",
  "doors closing",
  "ride arriving",
  "shift starting",
  "lunch break ending",
  "rain starting",
  "venue closing",
  "friend arriving",
  "taxi pulling up",
  "parking meter expiring",
  "pet needs attention",
  "child pickup time",
  "homework due soon",
  "next session beginning",
  "delivery arriving",
  "queue moving",
  "store closing announcement",
  "last train approaching",
  "movie starting",
  "performance starting",
  "teacher calling on student",
  "boarding begins",
  "security check",
  "network dropout",
  "noise too loud",
  "lost connection",
  "need to catch bus",
  "coffee spill cleanup",
  "manager calling",
  "fire alarm drill",
  "class bell rings",
  "doctor calls patient",
  "table ready",
  "reservation called",
  "subway doors opening",
  "volunteer duty starting",
  "curfew approaching",
  "family emergency text",
  "scheduled reminder",
  "app meeting alert"
] as const
export const closureReasons = CLOSURE_REASONS
